### ISSUE TITLE
想请教一下，生产环境下怎么跨域拿到卖座网的 api？

### ISSUE THREAD

**Issue by cody1991** [ChuckCZC/vue-demo-maizuo#2]
本地测试是没问题的，放线上的话就出现跨域的问题了 
demo:
http://cody1991.github.io/learn/Vue2/maizuo/dist/index.html#/home

**Comment by ChuckCZC** [comment]
@cody1991 本地测试是因为用了node进行了接口的代理，你直接放到github主页，没有服务器进行配合是不行的，你可以了解下相关的跨域知识

**Comment by cody1991** [comment]
嗯嗯，昨晚了解了下，大概了解了，谢谢～
