### ISSUE TITLE
想问下，手指在列表上滑动，当前列表的 hover 样式是怎么加上去的？ 

### ISSUE THREAD

**Issue by zhongs** [ChuckCZC/vue-demo-maizuo#3]

**Comment by ChuckCZC** [comment]
@zhongs 不好意思，不是很明白你指的是什么

**Comment by zhongs** [comment]
![Uploading QQ图片20170122154225.png…]()

**Comment by zhongs** [comment]
![Uploading QQ图片20170122154225.png…]()
不好意思，没讲清楚，现在截图了；

**Comment by zhongs** [comment]
![Uploading QQ图片20170122154225.png…]()
不好意思，没讲清楚，现在截图了；

**Comment by zhongs** [comment]
sorry！请问页面的“点击态”是怎么加上去的？
