### ISSUE TITLE
vue 指令问题   

### ISSUE THREAD

**Issue by yehoan** [ChuckCZC/vue-demo-maizuo#8]
亲爱的作者大牛 请收下渣渣的膝盖  我想咨询下就是film 里面的 v-scroll  你是怎么搞得  为什么我这边查了 vue 自带的指令里面没有v-scroll 这个指令 而且我试着写这个指令在vue 里面给我报错了 麻烦我想咨询下为什么 求教我怎么搞这个指令

**Comment by ChuckCZC** [comment]
那是自定义的指令，在main.js里面定义的 @yehoan
